#! /bin/bash

NOCOLOR='\033[0m'
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'

for f in "$@"
do
    echo -e ${GREEN}$f${NOCOLOR}
    # brew install poppler or brew install xpdf
    pdffonts $f
    echo
done

# Use ghostcript to embed fonts
# gs -q -dNOPAUSE -dBATCH -dPDFSETTINGS=/prepress -sDEVICE=pdfwrite -sOutputFile=output.pdf input.pdf


