#!/bin/bash

if [ $# -lt 1 ]; then
    echo "Usage: $0 input.pdf"
    echo "   or  $0 *.pdf"
    exit 1
fi

embed_fonts() {
	gs -q -dNOPAUSE -dBATCH -dPDFSETTINGS=/prepress -sDEVICE=pdfwrite -sOutputFile=temp.pdf $1; mv -f temp.pdf $1
}

for file in "$@"; do
    echo $(basename $file)
    embed_fonts "$file"
done
